# Generated by Django 3.2.8 on 2021-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
